---
sidebar: sidebar
permalink: air-disable-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: air.disable events
---

= air.disable events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== air.disable.async.delete.cli
*Severity*::
ALERT
*Description*::
This message occurs when any inconsistency is found with the async delete trashbin directory of a volume.
*Corrective Action*::
The "asynchronous directory delete from the client" feature has been disabled on this volume. To re-enable the feature, use the (privilege: advanced) "volume file async-delete client enable" command
*Syslog Message*::
The "async directory delete from the client" feature was disabled in volume %s, after an inconsistency was detected with the trashbin directory.
*Parameters*::
*volume* (STRING): Name of the volume.
*source* (STRING): Location of the failing metadata validation.

== air.disable.preserve.unlink
*Severity*::
NOTICE
*Description*::
This message occurs when any inconsistency is found with the preserve unlink trash directory of a volume.
*Corrective Action*::
This message indicates that an inconsistency was found with preserve unlink trash directory. And hence disabling preserve unlink feature on this volume.
*Syslog Message*::
Disabled preserve unlink feature in volume %s, after detecting inconsistency with trashbin directory.
*Parameters*::
*volume* (STRING): Name of the volume.
*source* (STRING): Location of the failing metadata validation.
